spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  # http://localhost:8010/{{context-path}}/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false